### ISSUE TITLE
Add TestNG to project

### ISSUE THREAD

**Issue by celicni** [DespotOfMorea/dictionary-app#4]
Add dependency to TestNG library to pom.xml. 

Write unit test for DBMethods.getTermID(). 

Use Mockito to mock database methods (opening and closing connections, execution of query). statement.executeQuery should be mocked and return some fixed value. Test how the method is behaving if different values are returned (some int, null, multiple results).

**Comment by DespotOfMorea** [comment]
I created a new [branch](https://github.com/DespotOfMorea/dictionary-app/tree/addingTestNG) with basic TestNG specific method.


Mockito cannot be used for static methods,so my question is should I use something else (PowerMockito has been suggested for this) or you have some other suggestion?
